# https://taskfile.dev

version: '2'

tasks:
  default:
      deps: [test, build]

  test:
    cmds:
      - cmd /c "del manifest.syso"
      - go test -v ./...

  build:
    cmds:
      - rsrc -manifest manifest.xml -o manifest.syso
      - go build -ldflags "-s -w -X main.Version={{.TAG}}" ./...
      - where upx && upx hosted{{exeExt}}
    vars:
        TAG:
            sh: git describe --abbrev=0
